name: Performance Benchmarks with bayesmark

on:
  workflow_dispatch:
    inputs:
      sampler-list:
        description: 'Sampler List: A list of samplers to check the performance. Should be a whitespace-separated list of Optuna samplers. Each sampler must exist under `optuna.samplers` or `optuna.integration`.'
        required: false
        default: 'TPESampler CmaEsSampler'
      sampler-kwargs-list:
        description: 'Sampler Arguments List: A list of sampler keyword arguments. Should be a whitespace-separated list of json format dictionaries.'
        required: false
        default: '{"multivariate":true,"constant_liar":true} {}'
      pruner-list:
        description: 'Pruner List: A list of pruners to check the performance. Should be a whitespace-separated list of Optuna pruners. Each pruner must exist under `optuna.pruners`.'
        required: false
        default: 'NopPruner'
      pruner-kwargs-list:
        description: 'Pruner Arguments List: A list of pruner keyword arguments. Should be a whitespace-separated list of json format dictionaries.'
        required: false
        default: '{}'
      budget:
        description: 'Number of trials'
        required: false
        default: '15'
      repeat:
        description: 'Number of Studies'
        required: false
        default: '3'
      plot-warmup:
        description: 'Include warm-up steps when plotting results'
        type: boolean
        default: false

jobs:
  benchmark:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # TODO Make it conditional for debug?
        # dataset: [breast, digits, iris, wine, diabetes]
        # model: [kNN, SVM, DT, RF, MLP-sgd, ada, linear]
        dataset: [diabetes, iris]
        model: [kNN, SVM]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Python libralies
      run: |
        python -m pip install --upgrade pip
        pip install --progress-bar off -U setuptools wheel
        # Install minimal dependencies and confirm that `import optuna` is successful.
        pip install --progress-bar off -U --pre optuna
        python -c 'import optuna'
        optuna --version
        pip install --progress-bar off bayesmark matplotlib pandas

    - name: Run performance benchmark
      run: |
        mkdir runs plots partial
        python run_bayesmark.py \
          --dataset ${{ matrix.dataset }} \
          --model ${{ matrix.model }} \
          --budget ${{ github.event.inputs.budget }} \
          --repeat ${{ github.event.inputs.repeat }} \
          --sampler-list '${{ github.event.inputs.sampler-list }}' \
          --sampler-kwargs-list '${{ github.event.inputs.sampler-kwargs-list }}' \
          --pruner-list '${{ github.event.inputs.pruner-list }}' \
          --pruner-kwargs-list '${{ github.event.inputs.pruner-kwargs-list }}' \
          --plot-warmup '${{ github.event.inputs.plot-warmup }}'
    
    - uses: actions/upload-artifact@v2
      with:
        name: benchmark-plots
        path: plots
    
    - uses: actions/upload-artifact@v2
      with:
        name: partial-reports
        path: partial

  build-report:
    needs: benchmark
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download partial reports
      uses: actions/download-artifact@v2
      with:
        name: partial-reports
        path: partial

    - name: Setup Python3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Python libralies
      run: |
        python -m pip install --upgrade pip
        pip install --progress-bar off -U setuptools wheel
        pip install --progress-bar off numpy scipy pandas Jinja2

    - name: Run benchmark report builder
      run: |
        mkdir report
        python report_bayesmark.py

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: benchmark-report
        path: report

    - name: Cleanup partial reports
      uses: geekyeggo/delete-artifact@v1
      with:
        name: partial-reports
